name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install MinGW
        run: choco install mingw -y
        env:
          chocolateyUseWindowsCompression: 'false'

      - name: Install dependencies
        run: npm install

      - name: Build Windows key listener
        run: npm run build:cpp

      - name: Build Windows app
        run: npm run build:win
        env:
          ELECTRON_BUILDER_PUBLISH: never

      - name: List artifacts
        run: dir exports
        shell: cmd

      - name: Upload Windows artifacts to draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            exports/AnimaleseTypingSetup*.exe
            exports/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build macOS key listener
        run: npm run build:swift

      - name: Build macOS app
        run: npm run build:mac
        env:
          ELECTRON_BUILDER_PUBLISH: never

      - name: List artifacts
        run: ls -l exports

      - name: Upload macOS artifacts to draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            exports/Animalese Typing*.dmg
            exports/latest-mac.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}